Doc 783 3.6
percona/psmdb-docs pull request #104
Opened 2018-09-28 17:47 UTC by borys-belinsky

2018-10-01 13:38 UTC, tplavcic commented
@borys-belinsky This will be released in the next release as BETA so we need a box with the message that this is beta quality and should be used in testing environments only. I think we have something similar in PS data at rest documentation.

2018-10-01 14:23 UTC, hrvojem requested changes

2018-10-01 14:23 UTC, hrvojem commented on source/data_at_rest_encryption.rst
> +.. |abbr.kmip| replace:: :abbr:`KMIP (Key Management Interoperability Protocol`
missing closing parentheses

2018-10-08 09:47 UTC, igorsol requested changes

2018-10-08 09:47 UTC, igorsol commented on source/.gitignore
> +ext/__pycache__
please add new line at end of file

2018-10-08 09:47 UTC, igorsol commented on source/data_at_rest_encryption.rst
> +- There are new configuration options to support |vault| and |amazon-aws| key
We don't have vault nor aws configuration options yet.

2018-10-08 09:47 UTC, igorsol commented on source/data_at_rest_encryption.rst
> +- There are new configuration options to support |vault| and |amazon-aws| key
Is this a typo? (new -> no)?

2018-10-08 09:47 UTC, igorsol commented on source/data_at_rest_encryption.rst
> +upstream solution, |PSMDB| supports the encryptionCipherMode option where you
Upstream have this option too: https://docs.mongodb.com/manual/reference/program/mongod/#cmdoption-mongod-encryptionciphermode

2018-10-08 09:47 UTC, igorsol commented on source/data_at_rest_encryption.rst
> +   $ mongod --encryptCipherMode AES256-GCM
Please replace encryptCipherMode -> encryptionCipherMode

2018-10-08 09:47 UTC, igorsol commented on source/data_at_rest_encryption.rst
> +   $ mongod --encryptCipherMode AES256-GCM
This command won't start mongod:

> /mongod --encryptionCipherMode AES256-GCM
> 2018-10-08T12:40:33.034+0300 F CONTROL  [main] Failed global initialization: BadValue: security.enableEncryption is required when security.encryptionCipherMode is specified

2018-10-08 09:47 UTC, igorsol commented on source/data_at_rest_encryption.rst
> +The key file must contain 32 bytes; each byte encoded in base64. You can generate a random
Formally 32 bytes encoded in base64 will give you more bytes so the actual file size will be something like 45 bytes. I think this can be reworded.

2018-10-08 09:47 UTC, igorsol commented on source/data_at_rest_encryption.rst
> +key and save it to a file by usiing the |openssl| command:
typo: usiing

2018-10-08 09:47 UTC, igorsol commented on source/data_at_rest_encryption.rst
> +
Ugly spaces at the end of line

2018-10-08 12:21 UTC, tplavcic requested changes

2018-10-08 12:21 UTC, tplavcic commented on source/data_at_rest_encryption.rst
> +   $ openssl rand -base64 32 > mongodb-keyfile
I think this should also include: `chmod 600 mongodb-keyfile` and some wording that the file should be accessible only by the owner of mongod process.

2018-10-09 17:33 UTC, borys-belinsky commented on source/data_at_rest_encryption.rst
> +
:)

2018-10-10 14:46 UTC, igorsol approved these changes
Changes approved

2018-10-25 19:19 UTC, tplavcic approved these changes
LGTM

2018-10-30 15:20 UTC, hrvojem approved these changes

2018-10-30 15:20 UTC, merged

2018-10-31 20:07 UTC, timvaillancourt commented on source/data_at_rest_encryption.rst
> +services.
I think we should add detail to answer these questions:
1. What exactly is and is-not encrypted by this feature?
    - Data files
    - Journal
    - Oplog
    - Log files
2. "Should I expect slower performance?" - I think we should say there is a performance impact to encryption. We don't know the exact impact until we benchmark, so just a general comment is fine.