PSMDB-426: Update for v4.2.0-1
percona/psmdb-docs pull request #148
Opened 2019-09-06 18:51 UTC by borys-belinsky

2019-09-08 13:39 UTC, tplavcic requested changes

2019-09-08 13:39 UTC, tplavcic commented on source/install/apt.rst
>  * Ubuntu 14.04 LTS (Trusty Tahr)
`Debian 8 (jessie)` and `Ubuntu 14.04 LTS (Trusty Tahr)` not available any more

2019-09-08 13:39 UTC, tplavcic commented on source/install/tarball.rst
> +      percona-server-mongodb-4.2.0-1/binary/debian/jessie/x86_64/\
debian jessie binary not available, maybe put one from ubuntu bionic instead: percona-server-mongodb-4.2.0-1-bionic-x86_64.tar.gz
https://jenkins.percona.com/job/percona-server-mongodb-4.2-TARBALL-release/label_exp=min-bionic-x64/

2019-09-08 13:39 UTC, tplavcic commented on source/install/upgrade_from_40.rst
> +#. Remove |PSMDB| |prev-version| packages: :bash:`apt-get remove percona-server-mongodb-40*`
4.0 packages do not have major version in their name (this change happened in 4.0 line), so `percona-server-mongodb-40*` should be `percona-server-mongodb*`

2019-09-08 13:39 UTC, tplavcic commented on source/install/upgrade_from_40.rst
> +#. Remove |PSMDB| |prev-version| packages: :bash:`yum remove Percona-Server-MongoDB-40*`
same for rpm (no 40 in package name), but for rpm they are also all lowercase, so `Percona-Server-MongoDB-40*` should be `percona-server-mongodb*`

2019-09-09 11:03 UTC, tplavcic requested changes

2019-09-09 11:03 UTC, tplavcic commented on source/install/tarball.rst
> +      percona-server-mongodb-4.2.0-1/binary/debian/jessie/x86_64/\
First two lines still have Debian Jessie binary tarball link if I'm not missing something.

2019-09-09 11:25 UTC, igorsol approved these changes

2019-09-09 11:25 UTC, igorsol commented on source/install/yum.rst
> +It is recommended to intall |PSMDB| from official |percona| repositories:
Small typo in the word `intall`

2019-09-09 14:27 UTC, tplavcic approved these changes

2019-09-09 14:28 UTC, merged