PSMDB-539: Release notes - v4.2.2-3
percona/psmdb-docs pull request #170
Opened 2019-12-20 15:28 UTC by borys-belinsky

2019-12-20 15:50 UTC, igorsol requested changes

2019-12-20 15:50 UTC, igorsol commented on source/release_notes/4.2.2-3.rst
> +  shell was run from the `root` account.
This bug is not about running mongo shell from the root account. logApplicationMessage failed when it was executed by the mongo user authorized by pretty powerful built-in roles which should include right to execute this command.
WIth this fix logApplicationMessage can be executed by any user who has 'applicationMessage' privilege. For example this privilege exists in such built-in roles as 'clusterManager' and 'hostManager'.

2019-12-20 17:07 UTC, igorsol approved these changes

2019-12-21 00:23 UTC, akira-kurogane approved these changes
LGTM

2019-12-23 17:14 UTC, merged