PSMDB-674 Updated tarball install instructions for a generic tarball
percona/psmdb-docs pull request #246
Opened 2020-08-11 10:47 UTC by nastena1606

2020-08-11 12:59 UTC, sandraromanchenko requested changes

2020-08-11 12:59 UTC, sandraromanchenko commented on source/install/tarball.rst
> +      tar -xf percona-server-mongodb-3.6.3-1-x86_64.glibc2.12.tar.gz
Filename should contain proper version name - percona-server-mongodb-3.6.19-7.0-x86_64.glibc2.12.tar.gz, the same version name should be in URL

2020-08-11 13:38 UTC, sandraromanchenko approved these changes

2020-08-12 11:53 UTC, Sudokamikaze approved these changes

2020-08-13 07:06 UTC, merged