PSMDB-685 Updated install docs
percona/psmdb-docs pull request #257
Opened 2020-08-27 08:51 UTC by nastena1606

Added a step to enable a psmdb-36 repo;
Replaced service * mongod with systemctl mongod * commands;
Removed notes about using systemctl command.

2020-08-27 09:35 UTC, EvgeniyPatlan approved these changes

2020-08-27 10:18 UTC, sandraromanchenko requested changes

2020-08-27 10:18 UTC, sandraromanchenko commented on source/install/yum.rst
In install section please change Percona-Server-MongoDB-34 to Percona-Server-MongoDB-36

2020-08-27 12:04 UTC, sandraromanchenko approved these changes

2020-09-17 13:28 UTC, sandraromanchenko approved these changes

2020-09-17 13:33 UTC, merged