Doc: LDAP referrals and connection pool support
percona/psmdb-docs pull request #291
Opened 2020-10-30 16:01 UTC by nastena1606

2020-10-30 16:04 UTC, sandraromanchenko requested changes

2020-10-30 16:04 UTC, sandraromanchenko commented on source/authentication.rst
> +      ldapFollowReferrals: 1
despite '1' is a valid value, for boolean options, IMHO, it's preferable using true/false values, it's less confusing

2020-10-30 16:07 UTC, sandraromanchenko approved these changes
LGTM

2020-10-30 16:33 UTC, dutow approved these changes

2020-11-02 06:10 UTC, akira-kurogane approved these changes
LGTM

2020-11-02 14:16 UTC, merged