PSMDB-943 Release notes 5.0.3
percona/psmdb-docs pull request #429
Opened 2021-10-11 15:33 UTC by nastena1606

Added warning to 5.0.2

modified:   source/conf.py
	modified:   source/release_notes/5.0.2-1.rst
	new file:   source/release_notes/5.0.3-2.rst
	modified:   source/release_notes/index.rst

2021-10-11 18:21 UTC, spron-in commented on source/release_notes/5.0.3-2.rst
> +   Please upgrade to MongoDB 5.0.3 or Percona Server for MongoDB 5.0.3-2 as soon as possible.
When I was quickly going through the notes this caught my eye. I believe the message we are trying to send is upgrade to 5.0.3-2 if you already have some other 5.0.X, right? 

Isn't it the same from above "Unless you are already running a version of MongoDB 5.0.x in your production environments, consider waiting a while longer for any other issues to be worked through."?

Let's keep one of them.

2021-10-11 18:21 UTC, spron-in commented on source/release_notes/5.0.3-2.rst
> +      * If you are running any version of MongoDB or Percona Server for MongoDB above v4.4.1, please upgrade to version 4.4.9 immediately. MongoDB version 4.4.9 and `Percona Server for MongoDB 4.4.9-
I would merge these two into one abstract. They are contradictory - we say stay on 4.4.1 and then we say upgrade to 4.4.9. Lets just be clear, that in 4.4.X we recommend 4.4.9.

2021-10-11 18:21 UTC, spron-in commented on source/release_notes/5.0.3-2.rst
> +      * If you are running any version of MongoDB 5.0.x or any version of MongoDB v4.4.2 or above, please follow closely all MongoDB Inc upstream recommendations regarding avoiding unclean shutdowns,
good one.

2021-10-11 18:21 UTC, spron-in commented on source/release_notes/5.0.3-2.rst
> +* `SERVER-58936 <https://jira.mongodb.org/browse/SERVER-58936>`_ - Unique Index constraint violations possible - can cause duplicate data - fixed in version 5.0.2.
Shall we mention it here? It is 5.0.3 release notes, not 5.0.2.

2021-10-11 18:21 UTC, spron-in commented on source/release_notes/5.0.3-2.rst
> +* `SERVER-60371 <https://jira.mongodb.org/browse/SERVER-60371>`_ - Deployments, previously running version 4.4.8 and upgraded to 4.4.9, could still experience the Duplicate Key error and Fatal assert
Any reason why we mention it here? How does it relate to 5.0.X ?

2021-10-12 17:10 UTC, igorsol requested changes

2021-10-12 17:10 UTC, igorsol commented on source/release_notes/5.0.2-1.rst
> +   This version is not recommended for production use due to the following critical issues: `WT-7984 <https://jira.mongodb.org/browse/WT-7984>`_ and `WT-7995 <https://jira.mongodb.org/browse/WT-7995>
Not recommended to use because of issues fixed in this release? It seems something is wrong here.

2021-10-12 17:10 UTC, igorsol commented on source/release_notes/5.0.2-1.rst
> +   This version is not recommended for production use due to the following critical issues: `WT-7984 <https://jira.mongodb.org/browse/WT-7984>`_ and `WT-7995 <https://jira.mongodb.org/browse/WT-7995>
Probably rewording is necessary

2021-10-13 05:39 UTC, nastena1606 commented on source/release_notes/5.0.2-1.rst
> +   This version is not recommended for production use due to the following critical issues: `WT-7984 <https://jira.mongodb.org/browse/WT-7984>`_ and `WT-7995 <https://jira.mongodb.org/browse/WT-7995>
Explicitly added version to make it clearer which version is affected and in which issues are fixed

2021-10-13 07:28 UTC, sandraromanchenko approved these changes

2021-10-13 08:51 UTC, spron-in approved these changes

2021-10-13 10:56 UTC, spron-in approved these changes

2021-10-13 14:10 UTC, igorsol commented on source/release_notes/5.0.2-1.rst
> +   This version is not recommended for production use due to the following critical issues: `WT-7984 <https://jira.mongodb.org/browse/WT-7984>`_ and `WT-7995 <https://jira.mongodb.org/browse/WT-7995>
Ah, sorry, now I see my mistake. Thank you for update

2021-10-13 14:10 UTC, igorsol approved these changes
LGTM

2021-10-14 15:19 UTC, merged