PSMDB-1057 Release notes 4.2.20-20
percona/psmdb-docs pull request #548
Opened 2022-05-17 15:07 UTC by nastena1606

modified:   source/conf.py
	new file:   source/release_notes/4.2.20-20.rst
	modified:   source/release_notes/index.rst

2022-05-18 11:08 UTC, igorsol requested changes
Is the `4.4.14.rst` file added to this PR by accident?

2022-05-18 11:08 UTC, igorsol commented on source/release_notes/4.2.20-20.rst
> +* :jirabug:`PSMDB-1011`: The ``kmipClientCertificateFile`` option now includes both the client private key and public certificate
This line should refer to PSMDB-1043

2022-05-18 12:39 UTC, igorsol approved these changes
Thanks

2022-05-20 10:52 UTC, spron-in commented on source/release_notes/4.2.20-20.rst
> +|PSMDB| now supports the master key rotation for data encrypted using the  :ref:`Keys Management Interoperability Protocol (KMIP) <kmip>` protocol (tech preview feature). This improvement allows user
```suggestion
|PSMDB| now supports the master key rotation for data-at-rest encryption using the  :ref:`Keys Management Interoperability Protocol (KMIP) <kmip>` protocol (tech preview feature). This improvement allows users to comply with regulatory standards for data security.
```

2022-05-20 10:56 UTC, spron-in approved these changes

2022-05-23 16:36 UTC, merged