3.4.1 1.1
percona/psmdb-docs pull request #55
Opened 2017-01-30 06:02 UTC by azhebel

2017-01-30 06:55 UTC, denis-protivenskii requested changes

2017-01-30 06:55 UTC, denis-protyvenskyi commented on source/changed_in_34.rst
> +The :ref:`mongorocks` storage engine is now based on RocksDB 4.11.2.
Rocks 4.13.5

2017-01-30 08:41 UTC, hrvojem commented on source/release_notes/3.4.1-1.1rc.rst
> +:Date: January 30, 2016
31st

2017-01-30 09:07 UTC, hrvojem requested changes
* Bump the version in conf.py
* s/2016/2017 for copyright there as well

2017-01-31 13:39 UTC, hrvojem commented on source/release_notes/3.4.1-1.1rc.rst
> +:Date: January 31, 2016
2017

2017-02-06 09:30 UTC, merged