PSMDB-1054 Described the kmipClientCertificatePassword option
percona/psmdb-docs pull request #567
Opened 2022-06-24 12:02 UTC by nastena1606

PSMDB-1045 Described the support for multiple KMIP servers

modified:   source/kmip.rst

2022-06-24 12:43 UTC, igorsol requested changes

2022-06-24 12:43 UTC, igorsol commented on source/kmip.rst
> +        - The hostname or IP address of the KMIP server. As of version 4.2.21-21, multiple KMIP servers are supported as the comma-separated list, e.g. ``kmip1.@example.com,kmip2.example.com``
@ character in the `kmip1.@example.com` seems to be a typo

2022-06-27 14:58 UTC, igorsol approved these changes

2022-06-28 13:10 UTC, sandraromanchenko approved these changes

2022-06-29 14:35 UTC, merged