PSMDB-1131 Release notes 4.2.22-22
percona/psmdb-docs pull request #590
Opened 2022-08-29 16:38 UTC by nastena1606

modified:   source/conf.py
new file:   source/release_notes/4.2.22-22.rst
modified:   source/release_notes/index.rst

2022-09-01 15:52 UTC, sandraromanchenko approved these changes

2022-09-05 15:32 UTC, igorsol requested changes

2022-09-05 15:32 UTC, igorsol commented on source/kmip.rst
> +While the data-at-rest encryption using the KMIP Protocol is in the tech preview stage, we recommend using it only for technical purposes as breaking changes can be introduced. With the ``kmipKeyIden
"technical purposes" -> "testing purposes"?

2022-09-05 15:34 UTC, nastena1606 commented on source/kmip.rst
> +While the data-at-rest encryption using the KMIP Protocol is in the tech preview stage, we recommend using it only for technical purposes as breaking changes can be introduced. With the ``kmipKeyIden
Thank you! Fixed

2022-09-05 16:03 UTC, igorsol approved these changes
LGTM

2022-09-06 12:46 UTC, merged