PSMDB-1234 Release notes 6.0.5-4
percona/psmdb-docs pull request #684
Opened 2023-03-22 12:13 UTC by nastena1606

modified:   .github/workflows/main.yml
	modified:   docs/comparison.md
	modified:   docs/glossary.md
	modified:   docs/index.md
	modified:   docs/release_notes/index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml
new file: docs/release_notes/6.0.5-4.md

2023-03-22 13:22 UTC, igorsol approved these changes
LGTM

2023-03-22 17:43 UTC, sandraromanchenko requested changes

2023-03-22 17:43 UTC, sandraromanchenko commented on docs/release_notes/6.0.5-4.md
> +fully-compatible, drop-in replacement for MongoDB 6.0.4 Community Edition.
```suggestion
fully-compatible, drop-in replacement for MongoDB 6.0.5 Community Edition.
```

2023-03-22 17:43 UTC, sandraromanchenko commented on docs/release_notes/6.0.5-4.md
> +| **Installation** | [Installing Percona Backup for MongoDB](../install/index.md) |
```suggestion
| **Installation** | [Installing Percona Server for MongoDB](../install/index.md) |
```
BTW RN for prev versions should also be fixed

2023-03-22 17:47 UTC, janwieremjewicz approved these changes

2023-03-23 23:34 UTC, kwilktx commented
@nastena1606 Found a reference to v6.0.4 in the new 6.0.5 release notes.

Please update. the description:  https://psmdb-docs-6-0-pr-684.onrender.com/release_notes/6.0.5-4.html

Change this: 
"Percona Server for MongoDB 6.0.5-4 is an enhanced, source-available, and highly-scalable database that is a fully-compatible, drop-in replacement for MongoDB 6.0.4 Community Edition."

to this:
"Percona Server for MongoDB 6.0.5-4 is an enhanced, source-available, and highly-scalable database that is a fully-compatible, drop-in replacement for MongoDB 6.0.5 Community Edition."

Still checking through the bugs, etc. Will let you know more in a bit

2023-03-23 23:37 UTC, kwilktx commented
Also under Release Highlights - would be good to immediately highlight that we ADDED support for AWS IAM

Release Highlights:

-"Added support for authentication using ..."

2023-03-23 23:51 UTC, kwilktx requested changes
Add the fix for these following bugs as they are ones that customers might likely run into:"


https://jira.mongodb.org/browse/SERVER-73266

Fixes deadlock that can occur during index creation


https://jira.mongodb.org/browse/SERVER-73009
Resolved problem in v6.0.x  version on clustered collections where returned results in increasing instead of the decreasing order requested

https://jira.mongodb.org/browse/SERVER-72512


https://jira.mongodb.org/browse/SERVER-71219

2023-03-24 11:44 UTC, sandraromanchenko approved these changes

2023-03-29 14:55 UTC, merged