PSMDB-1250 Release notes 4.4.21-20
percona/psmdb-docs pull request #703
Opened 2023-04-26 12:51 UTC by nastena1606

modified:   .github/workflows/main.yml
	new file:   docs/release_notes/4.4.21-20.md
	modified:   docs/release_notes/index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2023-04-26 17:02 UTC, sandraromanchenko requested changes

2023-04-26 17:02 UTC, sandraromanchenko commented on docs/release_notes/4.4.21-20.md
> +This release of Percona Server for MongoDB includes the improvements and bug fixes of MongoDB  Community Edition 5.0.16 and 5.0.17.
```suggestion
This release of Percona Server for MongoDB includes the improvements and bug fixes of MongoDB  Community Edition 4.4.20 and 4.4.21.
```

2023-05-04 07:16 UTC, sandraromanchenko requested changes

2023-05-04 07:16 UTC, sandraromanchenko commented on docs/release_notes/4.4.21-20.md
> +Find the full list of changes in the [MongoDB 4.4.20 Community Edition release notes](https://www.mongodb.com/docs/v4.4/release-notes/4.4/#4.4.20---apr-10--2023) and [MongoDB 4.4.21 Community Edition
```suggestion
Find the full list of changes in the [MongoDB 4.4.20 Community Edition release notes](https://www.mongodb.com/docs/v4.4/release-notes/4.4/#4.4.20---apr-10--2023) and [MongoDB 4.4.21 Community Edition release notes](https://www.mongodb.com/docs/v4.4/release-notes/4.4/#4.4.21---april-27--2023)
```

2023-05-04 11:24 UTC, sandraromanchenko approved these changes

2023-05-05 14:51 UTC, igorsol approved these changes
LGTM

2023-05-09 12:35 UTC, merged