PSMDB-1303 Release notes 6.0.8-6
percona/psmdb-docs pull request #745
Opened 2023-07-25 09:49 UTC by nastena1606

modified:   .github/workflows/main.yml
	new file:   docs/release_notes/6.0.8-6.md
	modified:   docs/release_notes/index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2023-07-25 12:12 UTC, igorsol approved these changes
LGTM

2023-08-02 09:38 UTC, sandraromanchenko requested changes

2023-08-02 09:38 UTC, sandraromanchenko commented on docs/release_notes/6.0.8-6.md
> +* [PSMDB-1280](https://jira.percona.com/browse/PSMDB-1280) - Improve PSMDB behavior on client disconnect when the `$backupCursorExtend` is opened
PSMDB-1289 is also included, pls add it to RN

2023-08-02 13:23 UTC, sandraromanchenko approved these changes

2023-08-03 10:50 UTC, kwilktx approved these changes
This comment is a little awkward - "The new ranges (or even possibly smaller sub-ranges) are moved or migrated by the balancer only when data needs to move."

Maybe change it to "Ranges (formerly chunks) are no longer auto-split and will be split only when they move across shards for distribution purposes."

Otherwise looks good. If need to we can wait until next time to fix the above sentence.  

Thanks,
Kimberly

2023-08-04 11:14 UTC, janwieremjewicz approved these changes

2023-08-08 15:08 UTC, merged