PSMDB-1306 Release notes 4.4.23-22
percona/psmdb-docs pull request #746
Opened 2023-07-26 11:20 UTC by nastena1606

modified:   .github/workflows/main.yml
	new file:   docs/release_notes/4.4.23-22.md
	modified:   docs/release_notes/index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2023-08-02 09:39 UTC, sandraromanchenko requested changes

2023-08-02 09:39 UTC, sandraromanchenko commented on docs/release_notes/4.4.23-22.md
> +| **Release date** | August 8, 2023 |
```suggestion
| **Release date** | August 14, 2023 |
```
Release was moved, pls fix

2023-08-02 09:39 UTC, sandraromanchenko commented on docs/release_notes/4.4.23-22.md
> +
PSMDB-1289 is also included, pls add it to RN

2023-08-09 15:07 UTC, sandraromanchenko requested changes

2023-08-09 15:07 UTC, sandraromanchenko commented on mkdocs-base.yml
> +          cover_subtitle: 4.4.23-22 (August 8, 2023)
```suggestion
          cover_subtitle: 4.4.23-22 (August 14, 2023)
```

2023-08-09 15:50 UTC, janwieremjewicz approved these changes

2023-08-09 17:28 UTC, igorsol approved these changes
LGTM

2023-08-14 15:44 UTC, merged