PSMDB-1307 Release notes 5.0.19-16
percona/psmdb-docs pull request #747
Opened 2023-07-26 13:07 UTC by nastena1606

modified:   .github/workflows/main.yml
	new file:   docs/release_notes/5.0.19-16.md
	modified:   docs/release_notes/index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2023-08-02 09:39 UTC, sandraromanchenko requested changes

2023-08-02 09:39 UTC, sandraromanchenko commented on docs/release_notes/5.0.19-16.md
> +
PSMDB-1289 is also included, pls add it to RN

2023-08-08 12:38 UTC, igorsol approved these changes
LGTM

2023-08-08 14:13 UTC, sandraromanchenko approved these changes

2023-08-09 15:48 UTC, janwieremjewicz approved these changes

2023-08-10 13:47 UTC, merged