PSMDB-1372 Pro builds documentation (6.0)
percona/psmdb-docs pull request #788
Opened 2023-11-06 13:23 UTC by nastena1606

2023-11-09 16:21 UTC, janwieremjewicz commented on docs/install/pro.md
> +Percona Server for MongoDB Pro packages include solutions typically demanded by large enterprises such as [FIPS compliance module](../fips.md) out of the box. Pro packages are available to Percona Cu
I would add some more "meat" here by adding something like "All of the features and solutions included in the Percona Server for MongoDB Pro builds are available in the source code. " in between this and the next

2023-11-09 16:21 UTC, janwieremjewicz commented on docs/install/source.md
> +- Basic builds. These include all Percona Server for MongoDB functionality except the solutions in pro builds. The packages provided by Percona are available to anyone.
shouldn't we capitalize Pro builds as the name?

2023-11-20 11:00 UTC, sandraromanchenko requested changes

2023-11-20 11:00 UTC, sandraromanchenko commented on docs/psmdb-pro.md
> +| [FIPS compliance module](fips.md)| [6.0.9-7](release_notes/6.0.9-7.md) | Enables US organizations to introduce FIPS-compliant encryption and thus meet the requirements towards data security |
```suggestion
| [FIPS support ](fips.md)| [6.0.9-7](release_notes/6.0.9-7.md) | Enables US organizations to introduce FIPS-compliant encryption and thus meet the requirements towards data security |
```
I wouldn't say we have added any module, it's rather FIPS support when PSMDB can use proper SSL/TLS libraries

2023-11-20 11:00 UTC, sandraromanchenko commented on docs/install/pro-repos.md
> +        Create the configuration file with the following contents
```suggestion
        Create the `/etc/yum.repos.d/psmdb-pro.repo` configuration file with the following contents
```

2023-11-20 11:00 UTC, sandraromanchenko commented on docs/install/pro-repos.md
> +        1. Create the `/etc/apt/sources.list.d/psmdb-pro` configuration file with the following contents
```suggestion
        1. Create the `/etc/apt/sources.list.d/psmdb-pro.list` configuration file with the following contents
```

2023-11-20 11:00 UTC, sandraromanchenko commented on docs/install/pro-repos.md
> +            ```ini title="/etc/apt/sources.list.d/psmdb-pro"
```suggestion
            ```ini title="/etc/apt/sources.list.d/psmdb-pro.list"
```

2023-11-20 11:00 UTC, sandraromanchenko commented on docs/install/pro-repos.md
> +            deb http://repo.percona.com/private/[CLIENTID]-[TOKEN]/psmdb-60/apt/ jammy main
```suggestion
            deb http://repo.percona.com/private/[CLIENTID]-[TOKEN]/psmdb-60-pro/apt/ OPERATING_SYSTEM main
```

2023-11-20 11:00 UTC, sandraromanchenko commented on docs/install/pro-repos.md
> +        ```ini
```suggestion
        ```ini title="/etc/yum.repos.d/psmdb-pro.repo"
```

2023-11-20 11:00 UTC, sandraromanchenko commented on docs/install/pro-repos.md
> +        baseurl=http://repo.percona.com/private/[CLIENTID]-[TOKEN]/psmdb-60-pro/yum/testing/$releasever/RPMS/x86_64
```suggestion
        baseurl=http://repo.percona.com/private/[CLIENTID]-[TOKEN]/psmdb-60-pro/yum/main/$releasever/RPMS/x86_64
```

2023-11-20 11:00 UTC, sandraromanchenko commented on docs/install/pro-repos.md
> +        $ apt install -y percona-server-mongodb
```suggestion
        $ apt install -y percona-server-mongodb-pro
```

2023-11-20 11:00 UTC, sandraromanchenko commented on docs/install/pro-repos.md
> +        $ yum install -y percona-server-mongodb
```suggestion
        $ yum install -y percona-server-mongodb-pro
```

2023-11-20 11:00 UTC, sandraromanchenko commented on docs/install/source.md
> +1. Create the folder where all build actions take place. For the steps below we use the `/tmp/Percona Server for MongoDB/test` folder.
```suggestion
1. Create the folder where all build actions take place. For the steps below we use the `/tmp/psmdb/test` folder.
```

2023-11-20 11:00 UTC, sandraromanchenko commented on docs/install/source.md
> +    $ wget https://raw.githubusercontent.com/percona/percona-server-mongodb/Percona Server for MongoDB-<tag>/percona-packaging/scripts/Percona_Server_for_MongoDB_builder.sh -O Percona_Server_for_Mong
```suggestion
    $ wget https://raw.githubusercontent.com/percona/percona-server-mongodb/psmdb-<tag>/percona-packaging/scripts/psmdb_builder.sh -O psmdb_builder.sh 
```

2023-11-20 11:00 UTC, sandraromanchenko commented on docs/install/source.md
> +        --branch=release-6.0.6-5 --psm_ver=6.0.6 --psm_release=5 --mongo_tools_tag=100.7.0 --enable_fipsmode=1 --jemalloc_tag=psmdb-3.2.11-3.1 --get_sources=1
```suggestion
        --branch=release-6.0.6-5 --psm_ver=6.0.6 --psm_release=5 --mongo_tools_tag=100.7.0 --full-featured=1 --jemalloc_tag=psmdb-3.2.11-3.1 --get_sources=1
```

2023-11-20 11:00 UTC, sandraromanchenko commented on docs/install/source.md
> +            --branch=release-6.0.6-5 --psm_ver=6.0.6 --psm_release=5 --mongo_tools_tag=100.7.0 --enable_fipsmode=1 --jemalloc_tag=psmdb-3.2.11-3.1 --build_deb=1
```suggestion
            --branch=release-6.0.6-5 --psm_ver=6.0.6 --psm_release=5 --mongo_tools_tag=100.7.0 --full-featured=1 --jemalloc_tag=psmdb-3.2.11-3.1 --build_deb=1
```

2023-11-20 11:00 UTC, sandraromanchenko commented on docs/install/source.md
> +            --branch=release-6.0.6-5 --psm_ver=6.0.6 --psm_release=5 --mongo_tools_tag=100.7.0 --enable_fipsmode=1 --jemalloc_tag=psmdb-3.2.11-3.1 --build_rpm=1
```suggestion
            --branch=release-6.0.6-5 --psm_ver=6.0.6 --psm_release=5 --mongo_tools_tag=100.7.0 --full-featured=1 --jemalloc_tag=psmdb-3.2.11-3.1 --build_rpm=1
```

2023-11-21 12:16 UTC, sandraromanchenko requested changes

2023-11-21 12:16 UTC, sandraromanchenko commented on docs/fips.md
> +The FIPS module in Percona Server for MongoDB is implemented in the same way, as in MongoDB Enterprise. It is available [in pro builds out of the box](psmdb-pro.md). You can also receive this module
```suggestion
The FIPS mode in Percona Server for MongoDB is implemented in the same way, as in MongoDB Enterprise. It is available [in pro builds out of the box](psmdb-pro.md). You can also receive this feature by [building Percona Server for MongoDB from source code](install/source.md).
```

2023-11-21 12:50 UTC, sandraromanchenko approved these changes

2023-11-21 12:52 UTC, sandraromanchenko requested changes

2023-11-21 12:52 UTC, sandraromanchenko commented on docs/install/update-pro.md
> +3. Install Percona Server for MongoDB packages
```suggestion
3. Install Percona Server for MongoDB PRO packages
```

2023-11-21 12:52 UTC, sandraromanchenko commented on docs/install/update-pro.md
> +        $ sudo yum install -y percona-server-mongodb-pro
```suggestion
        $ sudo yum install -y percona-server-mongodb-pro --allowerasing
```

2023-11-21 14:48 UTC, sandraromanchenko approved these changes

2023-11-24 14:58 UTC, janwieremjewicz approved these changes

2023-12-06 16:45 UTC, sandraromanchenko approved these changes

2023-12-07 12:19 UTC, sandraromanchenko requested changes

2023-12-07 12:19 UTC, sandraromanchenko commented on docs/install/source.md
> +        '
```suggestion
        bash -x ./psmdb_builder.sh --builddir=/tmp/psmdb/test --repo=https://github.com/percona/percona-server-mongodb.git \
        --branch=release-6.0.6-5 --psm_ver=6.0.6 --psm_release=5 --mongo_tools_tag=100.7.0 --jemalloc_tag=psmdb-3.2.11-3.1 --get_sources=1 --build_tarball=1
        '
```

2023-12-07 12:19 UTC, sandraromanchenko commented on docs/install/source.md
> +        $ docker run -ti -u root -v /tmp/psmdb:/tmp/psmdb rhel:9 sh -c '
```suggestion
        $ docker run -ti -u root -v /tmp/psmdb:/tmp/psmdb oraclelinux:7 sh -c '
```

2023-12-07 12:19 UTC, sandraromanchenko commented on docs/install/source.md
> +        --branch=release-6.0.6-5 --psm_ver=6.0.6 --psm_release=5 --mongo_tools_tag=100.7.0 --full-featured=1 --jemalloc_tag=psmdb-3.2.11-3.1 --get_sources=1
```suggestion
```

2023-12-07 12:19 UTC, sandraromanchenko commented on docs/install/source.md
> +    === "Pro build"
```suggestion
```

We don't provide tarballs for PRO builds

2023-12-07 12:19 UTC, sandraromanchenko commented on docs/install/source.md
> +1. Build source packages
```suggestion
1. Build src tarball
docker run -ti -u root -v /tmp/psmdb:/tmp/psmdb oraclelinux:8 sh -c '
set -o xtrace
cd /tmp/psmdb
bash -x ./psmdb_builder.sh --builddir=/tmp/psmdb/test --install_deps=1
bash -x ./psmdb_builder.sh --builddir=/tmp/psmdb/test --repo=https://github.com/percona/percona-server-mongodb.git --branch=release-6.0.6-5 --psm_ver=6.0.6 --psm_release=5 --mongo_tools_tag=100.7.0 --jemalloc_tag=psmdb-3.2.11-3.1 --get_sources=1'

2. Build source packages
```

2023-12-07 12:19 UTC, sandraromanchenko commented on docs/install/source.md
> +        $ docker run -ti -u root -v /tmp/psmdb:/tmp/psmdb ubuntu:jammy sh -c '
```suggestion
        $ docker run -ti -u root -v /tmp/psmdb:/tmp/psmdb oraclelinux:8 sh -c '
```

2023-12-07 16:26 UTC, sandraromanchenko commented on docs/install/source.md
>      $ ls -la /tmp/psmdb/test/source_tarball/
```suggestion
    $ ls -la /tmp/psmdb/test/tarball/
```

2023-12-07 16:26 UTC, sandraromanchenko commented on docs/install/source.md
>      -rw-r--r--. 1 root root 90398894 Jul  1 10:58 percona-server-mongodb-6.0.6-5.tar.gz
```suggestion
    -rw-r--r--. 1 root root 90398894 Jul  1 10:58 percona-server-mongodb-6.0.12-9-x86_64.glibc2.17.tar.gz
```

2023-12-08 10:20 UTC, sandraromanchenko requested changes

2023-12-08 10:20 UTC, sandraromanchenko commented on docs/install/source.md
> +            rw-r--r--. 1 root root 90398894 Jul  1 13:16 percona-server-mongodb-tools-pro_6.0.12-9.jammy_amd64.deb
```suggestion
            rw-r--r--. 1 root root 90398894 Jul  1 13:16 percona-server-mongodb-tools-6.0.12-9.jammy_amd64.deb  
```

2023-12-08 10:20 UTC, sandraromanchenko commented on docs/install/source.md
> +            rw-r--r--. 1 root root 90398894 Jul  1 13:16 percona-server-mongodb-tools-pro-6.0.12-9.el8.x86_64.rpm
```suggestion
            rw-r--r--. 1 root root 90398894 Jul  1 13:16 percona-server-mongodb-tools-6.0.12-9.el8.x86_64.rpm 
```

2023-12-08 10:20 UTC, sandraromanchenko commented on docs/install/source.md
> +            rw-r--r--. 1 root root 90398894 Jul  1 13:16 percona-server-mongodb-tools-debuginfo-pro-6.0.12-9.el8.x86_64.rpm
```suggestion
            rw-r--r--. 1 root root 90398894 Jul  1 13:16 percona-server-mongodb-tools-debuginfo-6.0.12-9.el8.x86_64.rpm
```

2023-12-08 10:20 UTC, sandraromanchenko commented on docs/install/source.md
> +    $ docker run -ti -u root -v /tmp/psmdb:/tmp/psmdb oraclelinux:7 sh -c '
```suggestion
    $ docker run -ti -u root -v /tmp/psmdb:/tmp/psmdb centos:7 sh -c '
```

2023-12-08 10:20 UTC, sandraromanchenko commented on docs/install/source.md
> +    $ docker run -ti -u root -v /tmp/psmdb:/tmp/psmdb oraclelinux:7 sh -c '
```suggestion
    $ docker run -ti -u root -v /tmp/psmdb:/tmp/psmdb centos:7 sh -c '
```

2023-12-08 10:20 UTC, sandraromanchenko commented on docs/install/source.md
> +            $ docker run -ti -u root -v /tmp/psmdb:/tmp/psmdb oraclelinux:7 sh -c '
```suggestion
            $ docker run -ti -u root -v /tmp/psmdb:/tmp/psmdb centos:7 sh -c '
```

2023-12-08 10:20 UTC, sandraromanchenko commented on docs/install/source.md
> +            $ docker run -ti -u root -v /tmp/psmdb:/tmp/psmdb oraclelinux:7 sh -c '
```suggestion
            $ docker run -ti -u root -v /tmp/psmdb:/tmp/psmdb centos:7 sh -c '
```

2023-12-08 10:20 UTC, sandraromanchenko commented on docs/install/source.md
> +1. Build the source tarball. It serves as the base for source packages. It is important to build source tarball using the oldest supported operating system, which is Oracle Linux 7.
```suggestion
1. Build the source tarball. It serves as the base for source packages. It is important to build source tarball using the oldest supported operating system, which is Centos 7.
```

2023-12-08 10:20 UTC, sandraromanchenko commented on docs/install/source.md
> +1. The following command builds tarballs of Percona Server for MongoDB 6.0.12-9 on Oracle Linux 7. Change the Docker image and the values for `--branch`, `--psm_ver`, `--psm_release` flags to build t
```suggestion
1. The following command builds tarballs of Percona Server for MongoDB 6.0.12-9 on Centos 7. Change the Docker image and the values for `--branch`, `--psm_ver`, `--psm_release` flags to build tarballs of a different version and on a different operating system.
```

2023-12-08 10:20 UTC, sandraromanchenko commented on docs/install/source.md
> +    * runs Docker daemon as the root user using the Oracle Linux 7 image
```suggestion
    * runs Docker daemon as the root user using the Centos 7 image
```

2023-12-08 10:20 UTC, sandraromanchenko commented on docs/install/source.md
> +    Note that to build source packages you still have to use the oldest supported operating system: Oracle Linux 7 for RPMs and Ubuntu 18.04 (Bionic Beaver) for DEB packages.
```suggestion
    Note that to build source packages you still have to use the oldest supported operating system: Centos 7 for RPMs and Ubuntu 18.04 (Bionic Beaver) for DEB packages. 
```

2023-12-08 10:32 UTC, sandraromanchenko approved these changes

2023-12-13 13:31 UTC, sandraromanchenko requested changes

2023-12-13 13:31 UTC, sandraromanchenko commented on docs/install/source.md
> +            rw-r--r--. 1 root root 90398894 Jul  1 13:16 percona-server-mongodb-dbg-pro_6.0.12-9.jammy_amd64.deb
```suggestion
            rw-r--r--. 1 root root 90398894 Jul  1 13:16 percona-server-mongodb-pro-dbg_6.0.12-9.jammy_amd64.deb  
```

2023-12-13 13:31 UTC, sandraromanchenko commented on docs/install/source.md
> +            rw-r--r--. 1 root root 90398894 Jul  1 13:16 percona-server-mongodb-debugsource-pro-6.0.12-9.el8.x86_64.rpm
```suggestion
            rw-r--r--. 1 root root 90398894 Jul  1 13:16 percona-server-mongodb-pro-debugsource-6.0.12-9.el8.x86_64.rpm 
```

2023-12-13 13:31 UTC, sandraromanchenko commented on docs/install/source.md
> +            rw-r--r--. 1 root root 90398894 Jul  1 13:16 percona-server-mongodb-mongos-debuginfo-pro-6.0.12-9.el8.x86_64.rpm
```suggestion
            rw-r--r--. 1 root root 90398894 Jul  1 13:16 percona-server-mongodb-mongos-pro-debuginfo-6.0.12-9.el8.x86_64.rpm 
```

2023-12-13 13:31 UTC, sandraromanchenko commented on docs/install/source.md
> +            rw-r--r--. 1 root root 90398894 Jul  1 13:16 percona-server-mongodb-server-debuginfo-pro-6.0.12-9.el8.x86_64.rpm
```suggestion
            rw-r--r--. 1 root root 90398894 Jul  1 13:16 percona-server-mongodb-server-pro-debuginfo-6.0.12-9.el8.x86_64.rpm 
```

2023-12-13 13:40 UTC, sandraromanchenko approved these changes

2023-12-14 15:43 UTC, merged