PSMDB-1370 Release notes 5.0.22-19
percona/psmdb-docs pull request #789
Opened 2023-11-06 17:44 UTC by nastena1606

modified:   .github/workflows/main.yml
	new file:   docs/release_notes/5.0.22-19.md
	modified:   docs/release_notes/index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2023-11-07 13:53 UTC, igorsol requested changes

2023-11-07 13:53 UTC, igorsol commented on docs/release_notes/5.0.22-19.md
> +
We have PSMDB-1241 (new feature) in this release

2023-11-08 08:43 UTC, sandraromanchenko requested changes

2023-11-08 08:43 UTC, sandraromanchenko commented on mkdocs-base.yml
> +      - release_notes/5.0.20-19.md
```suggestion
      - release_notes/5.0.22-19.md
```

2023-11-08 11:13 UTC, sandraromanchenko approved these changes

2023-11-08 19:29 UTC, igorsol approved these changes

2023-11-09 16:13 UTC, merged