Psmdb 1376 release notes 7.0.4
percona/psmdb-docs pull request #796
Opened 2023-11-30 10:28 UTC by nastena1606

2023-11-30 11:35 UTC, igorsol approved these changes
LGTM

2023-11-30 14:49 UTC, sandraromanchenko requested changes

2023-11-30 14:49 UTC, sandraromanchenko commented on mkdocs-base.yml
> +          cover_subtitle: 7.0.3-2 (December 11, 2023)
```suggestion
          cover_subtitle: 7.0.4-2 (December 11, 2023)
```

2023-11-30 14:49 UTC, sandraromanchenko commented on docs/release_notes/index.md
> +* [Percona Server for MongoDB 7.0.4-2 (2023-12-11)](7.0.3-2.md)
```suggestion
* [Percona Server for MongoDB 7.0.4-2 (2023-12-11)](7.0.4-2.md)
```

2023-11-30 15:26 UTC, kwilktx commented
@nastena1606 @igorsol @sandraromanchenko 

I think we need to mention the Downgrade and fCV changes and the Backward-Incompatible Features - It is too big a thing not to mention - with consequences

Starting in MongoDB 7.0:
    Binary downgrades are no longer supported for MongoDB Community Edition.
    
    The [setFeatureCompatibilityVersion](https://www.mongodb.com/docs/v7.0/reference/command/setFeatureCompatibilityVersion/#mongodb-dbcommand-dbcmd.setFeatureCompatibilityVersion) command requires an additional parameter, confirm, which must be set to true to upgrade or downgrade fCV.
    
    https://www.mongodb.com/docs/v7.0/release-notes/7.0/#downgrade-considerations
    
https://www.mongodb.com/docs/v7.0/release-notes/7.0-compatibility/#std-label-7.0-downgrade-incompatible

wildcard indexes, config servers that store data, columnar indexes that would have to be removed.

Other than that the bugs that you mention as fixed look good.

2023-12-04 13:08 UTC, sandraromanchenko requested changes

2023-12-04 13:08 UTC, sandraromanchenko commented on docs/release_notes/7.0.4-2.md
> +* Due to [time series sharded cluster operation routing issue](https://jira.mongodb.org/browse/SERVER-80203) occurred in MongoDB version 7.0.1 - 7.0.3 and fixed in version 7.0.4, follow closely the u
```suggestion
* Due to [time series sharded cluster operation routing issue](https://jira.mongodb.org/browse/SERVER-80203) occurred in MongoDB version 7.0.1 - 7.0.2 and fixed in version 7.0.3, follow closely the upstream remediation recommendations to identify and recover orphanated collections.
```

2023-12-04 13:20 UTC, sandraromanchenko approved these changes

2023-12-07 10:30 UTC, sandraromanchenko approved these changes

2023-12-11 20:09 UTC, merged