PSMDB-1386 Release notes 6.0.12
percona/psmdb-docs pull request #797
Opened 2023-12-04 16:58 UTC by nastena1606

modified:   .github/workflows/main.yml
	new file:   docs/release_notes/6.0.12-9.md
	modified:   docs/release_notes/index.md
	modified:   mkdocs-base.yml

2023-12-05 16:19 UTC, igorsol requested changes

2023-12-05 16:19 UTC, igorsol commented on docs/release_notes/6.0.12-9.md
> +   If you are using time series collections, upgrade to MongoDB 7.0.4 or Percona Server for MongoDB 7.0.4-2 as soon as possible. Please follow closely the upstream recommendations to identify and pre
Upgrade to 7.0.4 or to 6.0.12?

2023-12-06 07:49 UTC, olexandr-havryliak approved these changes

2023-12-07 10:39 UTC, sandraromanchenko approved these changes

2023-12-07 16:49 UTC, igorsol approved these changes

2023-12-13 14:06 UTC, igorsol approved these changes

2023-12-14 15:44 UTC, merged