PSMDB-1388 Release notes 4.4.26-25
percona/psmdb-docs pull request #800
Opened 2023-12-13 13:21 UTC by nastena1606

modified:   .github/workflows/main.yml
	modified:   .gitignore
	modified:   docs/404.md
	new file:   docs/release_notes/4.4.26-25.md
	modified:   docs/release_notes/index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2023-12-13 14:07 UTC, igorsol approved these changes

2023-12-13 15:19 UTC, sandraromanchenko requested changes

2023-12-13 15:19 UTC, sandraromanchenko commented on docs/release_notes/4.4.26-25.md
> +# Percona Server for MongoDB 4.4.26-25 (2023-10-16)
```suggestion
# Percona Server for MongoDB 4.4.26-25 (2023-12-18)
```

2023-12-13 15:21 UTC, sandraromanchenko requested changes

2023-12-13 15:21 UTC, sandraromanchenko commented on docs/release_notes/4.4.26-25.md
> +
* [AWS IAM authentication](../aws-iam.md) is now generally available, enabling you to use this functionality in production environments.

* Percona Server for MongoDB now includes telemetry that fills in the gaps in our understanding of how you use Percona Server for MongoDB to improve our products. Participation in the anonymous program is optional. You can opt-out if you prefer not to share this information. [Read more about Telemetry](../telemetry.md).

2023-12-15 10:42 UTC, sandraromanchenko approved these changes

2023-12-18 14:22 UTC, merged