Fix for DOC-727, documenting deprecation of MongoRocks
percona/psmdb-docs pull request #82
Opened 2018-03-28 22:16 UTC by fiowro

2018-03-28 22:26 UTC, RoelVdP requested changes
@tplavcic would you please do an all-over tech review? Including the final page as-is. Thanks

2018-03-28 22:26 UTC, RoelVdP commented on source/mongorocks.rst
> +   failing tests for those.
Please change to;
is limited to 3.4, so 3.6 functionality cannot be used. Read/write concern majority is not safe to use.

2018-03-28 22:26 UTC, RoelVdP commented on source/mongorocks.rst
> +You can select a storage engine using the ``--storageEngine``
This needs a lead-in. For example "If you still would like to use the deprecated MongoRocks storage engine, please use the ``--storageEngine rocksdb`` command-line option, accompanied by ...."

2018-03-28 22:26 UTC, RoelVdP commented on source/mongorocks.rst
> +configuration file (by default, :file:`/etc/mongod.conf`).
... configuration file (by default, :file:`/etc/mongod.conf`) as shown below.

2018-03-29 06:14 UTC, tplavcic commented
This line in "Using MongoRocks" is not working: `sed -i '/engine: \*rocksdb/s/#//g' /etc/mongod.conf` from what I see it should be `sed -i '/engine: *rocksdb/s/#//g' /etc/mongod.conf`.
And since useDeprecatedMongoRocks is needed now I think this line should be added after that one: `sed -i '/engine: *rocksdb/a\  useDeprecatedMongoRocks: true' /etc/mongod.conf`

By looking in github I don't see that the warning of deprecation is boxed and colored but I think it will be on our web page if that is true then it's ok.

Should we add `useDeprecatedMongoRocks` in the options list? Most probably yes, although it's a mandatory switch so I'm not 100% on this one.

No other issues I see.

2018-03-29 14:13 UTC, fiowro commented
And what do you think about just removing these sed lines from the 3.6 doc? They are just to uncomment "engine: rocksdb" line (which is commented in the example mongod.conf). Adding “useDeprecatedMongoRocks” by sed would either be capable to produce duplicate lines in config or would involve some complicated and unreadable sed magic… 

Necessary modifications to config file are already described, and later there is an example, so removing sed commands would probably do nothing wrong...

2018-04-09 18:49 UTC, tplavcic commented
@fiowro Removing those sed lines from docs works for me.

2018-04-12 11:17 UTC, tplavcic commented
LGTM, @RoelVdP if no additional comments can you please approve PR so that it can be merged. Thanks!

2018-04-12 11:24 UTC, tplavcic commented
@fiowro found one small issue on upgrade page, the step:
```#. Add ``useDeprecatedMongoRocks: true`` line into the config file.```
should only apply if the user is using MongoRocks, so maybe something like:
```#. Add ``useDeprecatedMongoRocks: true`` line into the config file if using MongoRocks storage engine.```

2018-04-12 13:36 UTC, tplavcic requested changes
As already discussed one small change is still needed on the upgrade page and then it can be merged.
#. Add ``useDeprecatedMongoRocks: true`` line into the config file.
should only apply if the user is using MongoRocks, so maybe something like:
#. Add ``useDeprecatedMongoRocks: true`` line into the config file if using MongoRocks storage engine.

2018-04-13 01:45 UTC, RoelVdP requested changes

2018-04-13 01:45 UTC, RoelVdP commented on source/install/upgrade_from_34.rst
> +    sed -i '/engine: *rocksdb/a\ useDeprecatedMongoRocks: true' /etc/mongod.conf
`sed -i '/engine:[ \t]*rocksdb/a\ useDeprecatedMongoRocks: true' /etc/mongod.conf`

Is safer as it includes tabs besides spaces

2018-04-13 01:45 UTC, RoelVdP commented on source/install/upgrade_from_34.rst
> +    sed -i '/engine: *rocksdb/a\ useDeprecatedMongoRocks: true' /etc/mongod.conf
As above

2018-04-13 01:46 UTC, RoelVdP commented on source/install/upgrade_from_34.rst
> +    sed -i '/engine: *rocksdb/a\ useDeprecatedMongoRocks: true' /etc/mongod.conf
Good to merge otherwise

2018-04-13 01:50 UTC, RoelVdP approved these changes

2018-04-18 06:30 UTC, tplavcic approved these changes
LGTM

2018-04-18 07:20 UTC, merged

2020-01-29 22:18 UTC, peterschwaller commented
Dummy comment to trigger sync to Jira.  Please ignore.