PSMDB-1424 Release notes 5.0.25-22
percona/psmdb-docs pull request #830
Opened 2024-03-12 15:08 UTC by nastena1606

modified:   .github/workflows/main.yml
	new file:   docs/release_notes/5.0.25-22.md
	modified:   docs/release_notes/index.md
	modified:   mkdocs-base.yml
	deleted:    runtime.txt
	modified:   variables.yml

2024-03-14 10:14 UTC, igorsol commented on docs/release_notes/5.0.25-22.md
> +* [PSMDB-1434](https://perconadev.atlassian.net/browse/PSMDB-1434) - Fixed the auditing behavior not to log CRUD operations
This title is not clear to me. Was there not enough CRUD operations logged or vice versa? (In fact we removed excessive logging).

2024-03-15 11:32 UTC, igorsol approved these changes

2024-04-04 14:03 UTC, sandraromanchenko requested changes

2024-04-04 14:03 UTC, sandraromanchenko commented on variables.yml
> +release: '5.0.25-22'
```suggestion
release: '5.0.26-22'
```

2024-04-04 14:03 UTC, sandraromanchenko commented on docs/release_notes/index.md
> +* [Percona Server for MongoDB 5.0.25-22 (2024-04-09)](5.0.26-22.md)
```suggestion
* [Percona Server for MongoDB 5.0.26-22 (2024-04-09)](5.0.26-22.md)
```

2024-04-05 12:50 UTC, sandraromanchenko approved these changes

2024-04-09 15:35 UTC, merged