PSMDB-1429 Release notes 6.0.14-11
percona/psmdb-docs pull request #835
Opened 2024-03-19 08:40 UTC by nastena1606

modified:   .github/workflows/main.yml
	modified:   docs/release_notes/6.0.13-10.md
	new file:   docs/release_notes/6.0.14-11.md
	modified:   docs/release_notes/index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-03-19 13:23 UTC, igorsol requested changes

2024-03-19 13:23 UTC, igorsol commented on docs/release_notes/6.0.13-10.md
> +    The issue is fixed upstream in versions 4.4.29, 5.0.25, 6.0.14 and 7.0.6 and in Percona Server for MongoDB 4.4.29-28, 5.0.25-22, 6.0.14-11 and 7.0.6-4. Now, configuring MongoDB to use TLS require
We will skip 7.0.6 so the next released version will be 7.0.7-4

2024-03-19 13:23 UTC, igorsol commented on docs/release_notes/6.0.14-11.md
> +    The issue is fixed upstream in versions 4.4.29, 5.0.25, 6.0.14 and 7.0.6 and in Percona Server for MongoDB 4.4.29-28, 5.0.25-22, 6.0.14-11 and 7.0.6-4. Now, configuring MongoDB to use TLS require
We will skip 7.0.6 so the next released version will be 7.0.7-4

2024-03-22 13:15 UTC, sandraromanchenko requested changes

2024-03-22 13:15 UTC, sandraromanchenko commented on docs/release_notes/6.0.13-10.md
> +    The issue is fixed upstream in versions 4.4.29, 5.0.25, 6.0.14 and 7.0.6 and in Percona Server for MongoDB 4.4.29-28, 5.0.25-22, 6.0.14-11 and 7.0.6-4. Now, configuring MongoDB to use TLS require
```suggestion
    The issue is fixed upstream in versions 4.4.29, 5.0.25, 6.0.14 and 7.0.6 and in Percona Server for MongoDB 4.4.29-28, 5.0.25-22, 6.0.14-11 and 7.0.7-4. Now, configuring MongoDB to use TLS requires specifying the value for the `--tlsCAFile` flag, the `net.tls.CAFile `configuration option, or the `tlsUseSystemCA` parameter.
```

2024-03-22 14:00 UTC, sandraromanchenko approved these changes

2024-03-22 14:30 UTC, igorsol approved these changes

2024-03-26 09:49 UTC, janwieremjewicz approved these changes

2024-03-26 15:14 UTC, merged