PSMDB-1450 Release notes 6.0.15-12
percona/psmdb-docs pull request #855
Opened 2024-04-23 17:20 UTC by nastena1606

new file:   docs/release_notes/6.0.15-12.md
	modified:   docs/release_notes/index.md
	modified:   mkdocs-base.yml

2024-04-23 18:33 UTC, igorsol requested changes

2024-04-23 18:33 UTC, igorsol commented on docs/release_notes/6.0.15-12.md
> +
PSMDB-1418 should be mentioned in these release notes

2024-04-24 09:53 UTC, igorsol approved these changes
LGTM

2024-04-26 12:27 UTC, sandraromanchenko requested changes

2024-04-26 12:27 UTC, sandraromanchenko commented on docs/release_notes/6.0.15-12.md
> +fully-compatible, drop-in replacement for MongoDB Community Edition 6.0.14
```suggestion
fully-compatible, drop-in replacement for MongoDB Community Edition 6.0.15
```

2024-04-26 12:27 UTC, sandraromanchenko commented on docs/release_notes/6.0.15-12.md
> +The issues are fully fixed in MongoDB  4.4.29, 5.0.25, 6.0.14, 7.0.8, and are included in Percona Server for MongoDB 4.4.29-28, 5.0.26-22,6.0.14-11 and 7.0.8-5. If you are using sharded multi-documen
```suggestion
The issues are fully fixed in MongoDB  4.4.29, 5.0.25, 6.0.14, 7.0.8, and are included in Percona Server for MongoDB 4.4.29-28, 5.0.26-22,6.0.14-11 and 7.0.8-5. If you are using sharded multi-document transactions or queryable encryption, upgrade to Percona Server for MongoDB 6.0.14-11 or later versions as soon as possible. Please follow closely the upstream recommendations for mitigation and remediation outlined in [Sharded multi-document transactions may perform operations using inconsistent sharding metadata](https://www.mongodb.com/alerts/critical-alert-sharding-txn-issues-apr-2024) alert.
```

2024-04-29 11:04 UTC, sandraromanchenko approved these changes

2024-04-30 14:22 UTC, merged