PSMDB-1487 Docs for 8.0
percona/psmdb-docs pull request #895
Opened 2024-07-26 07:06 UTC by nastena1606

2024-08-05 08:46 UTC, radoslawszulgo commented
Change in docs/index.md missing - it still displays 7.0

2024-10-28 13:55 UTC, sandraromanchenko requested changes

2024-10-28 13:55 UTC, sandraromanchenko commented on docs/install/tarball.md
> +You can find links to the binary tarballs under the *Generic Linux* menu item on the [Percona website](https://www.percona.com/downloads/percona-server-mongodb-6.0/)
```suggestion
You can find links to the binary tarballs under the *Generic Linux* menu item on the [Percona website](https://www.percona.com/downloads/percona-server-mongodb-8.0/)
```

2024-10-28 13:55 UTC, sandraromanchenko commented on mkdocs-base.yml
> +          cover_subtitle:
```suggestion
          cover_subtitle: 8.0.1-1 (October 30, 2024)
```

2024-10-28 13:55 UTC, sandraromanchenko commented on docs/psmdb-pro.md
> +Percona Server for MongpDB Pro is available starting with version [7.0.4-2](release_notes/https://docs.percona.com/percona-server-for-mongodb/release_notes/7.0.4-2.html).
```suggestion
Percona Server for MongoDB Pro is available starting with version [8.0.1-1](release_notes/https://docs.percona.com/percona-server-for-mongodb/release_notes/8.0.1-1.html).
```

2024-10-28 13:55 UTC, sandraromanchenko commented on docs/psmdb-pro.md
> +| [FIPS support ](fips.md)| [7.0.4-2](https://docs.percona.com/percona-server-for-mongodb/release_notes/7.0.4-2.html) | FIPS mode provides a way to use FIPS-compliant encryption and run the Percona S
```suggestion
| [FIPS support ](fips.md)| [8.0.1-1](https://docs.percona.com/percona-server-for-mongodb/release_notes/8.0.1-1.html) | FIPS mode provides a way to use FIPS-compliant encryption and run the Percona Server for MongoDB with the FIPS-140 certified library for OpenSSL. This helps customers meet minimum security requirements for cryptographic modules and testing in both hardware and software. |
```

2024-10-28 14:13 UTC, sandraromanchenko approved these changes

2024-10-30 15:52 UTC, nastena1606 commented on docs/install/source.md
> +    $ gcc g++ cmake curl libssl-dev libldap2-dev libkrb5-dev libcurl4-openssl-dev libsasl2-dev liblz4-dev libpcap-dev libbz2-dev libsnappy-dev zlib1g-dev libzlcore-dev liblzma-dev ibext2fs-dev e2fsli
```suggestion
    $ sudo apt install -y gcc g++ cmake curl libssl-dev libldap2-dev libkrb5-dev libcurl4-openssl-dev libsasl2-dev liblz4-dev libpcap-dev libbz2-dev libsnappy-dev zlib1g-dev libzlcore-dev liblzma-dev ibext2fs-dev e2fslibs-dev bear
```

2024-11-21 12:20 UTC, radoslawszulgo requested changes
Please remove distro ;)

2024-12-09 11:24 UTC, nastena1606 commented
> Please remove distro ;)

@radoslawszulgo we don't list distro in this doc set

2024-12-17 16:06 UTC, merged