PSMDB-1284 Doc: File copy based initial sync
percona/psmdb-docs pull request #912
Opened 2024-08-23 14:44 UTC by nastena1606

new file:   docs/initial-sync.md
	modified:   docs/psmdb-pro.md
	modified:   mkdocs-base.yml

2025-06-25 12:20 UTC, igorsol approved these changes
Looks good but exact versions should be reviewed everywhere when we are ready for release

2025-06-25 12:20 UTC, igorsol commented on docs/initial-sync.md
> +When a new member joins the replica set, it receives the data from the primary node via the initial sync.
Initial sync source is not always the primary node. There is special algorithm which select initial sync source among all replset nodes.

2025-06-25 12:20 UTC, igorsol commented on docs/initial-sync.md
> +Starting with version 7.0.12, you can select **file copy based** as the initial sync method. This is the physical copying of the data files from source to target. This sync method is faster than logi
It will likely be other version, not 7.0.12

2025-06-25 12:20 UTC, igorsol commented on docs/initial-sync.md
> +File copy-based initial sync is implemented in the same way as in MongoDB Enterprise. For workflow and known limitations, refer to [MongoDB documentation](https://www.mongodb.com/docs/manual/core/rep
I would suggest to change "implemented the same way" to "implemented in a similar way".
Ideally we need to distinguish between internal implementation and user-facing configuration and behavior. Internal implementation is definitely not the same.

2025-06-25 12:27 UTC, nastena1606 commented on docs/initial-sync.md
> +When a new member joins the replica set, it receives the data from the primary node via the initial sync.
Updated

2025-06-25 12:48 UTC, nastena1606 commented on docs/initial-sync.md
> +File copy-based initial sync is implemented in the same way as in MongoDB Enterprise. For workflow and known limitations, refer to [MongoDB documentation](https://www.mongodb.com/docs/manual/core/rep
@radoslawszulgo, do you think we need to add details on how FCBIS is implemented in PSMDB? Add a sync workflow for example?

2025-06-27 16:00 UTC, radoslawszulgo commented on docs/initial-sync.md
> +The default initial sync method is logical, during which Percona Server for MongoDB clones all databases except the `local` database, builds all collection indexes, pulls oplog records and applies th
I'd remove this paragraph. Optionally, move this till the end and shortly inform that there's the other (default) initial sync method.

2025-06-27 16:02 UTC, radoslawszulgo commented on docs/initial-sync.md
> +File copy-based initial sync is implemented in a similar way as in MongoDB Advanced and has the same configuration options. For workflow and known limitations, refer to [MongoDB documentation](https:
At best we should review and have our own list of limitations rather than redirecting to the Upstream - if they fix something and remove the limitation it doesn't mean it's fixed in our case.

2025-07-09 09:13 UTC, olexandr-havryliak approved these changes

2025-07-15 14:42 UTC, igorsol requested changes

2025-07-15 14:42 UTC, igorsol commented on docs/initial-sync.md
> +To select the initial sync method, specify the following configuration in the configuration file for the target node:
not sure, maybe following wording is better?
> ... specify the following __parameter__ in the configuration file ...

2025-07-15 14:42 UTC, igorsol commented on docs/initial-sync.md
> +To select the initial sync method, specify the following configuration in the configuration file for the target node:
or consider this:
> ... specify the __initial sync method__ in the configuration file ...

2025-07-15 14:42 UTC, igorsol commented on docs/initial-sync.md
> +You can only set this configuration at startup.
consider this:
> This server parameter can only be set at startup

2025-07-15 14:42 UTC, igorsol commented on docs/initial-sync.md
> +1. The new node (also referred to as the target node) selects for the source node for the sync. This sync source is typically the node that responded first and has the passing configuration (e.g. it
In this part:
> selects for the source node for the sync

the first "for" is redundant

2025-07-15 14:42 UTC, igorsol commented on docs/initial-sync.md
> +4. If the lag between the sync source differs and the target exceeds the defined threshold, the target node opens the `$backupCursorExtended` to retrieve the changes. Depending on the file copy durat
> If the lag between the sync source differs and the target exceeds the defined threshold

The "diiffers" should be removed

2025-07-15 14:42 UTC, igorsol commented on docs/initial-sync.md
> +4. If the lag between the sync source differs and the target exceeds the defined threshold, the target node opens the `$backupCursorExtended` to retrieve the changes. Depending on the file copy durat
I think it would be better to say that target node "executes" $backupCursorExtend instead of "opens"

2025-07-15 14:42 UTC, igorsol commented on docs/initial-sync.md
> +5. When the files are copied and the lag between the sync source and the target is acceptable, the target node closes the `$backupCursor`.
Please replace '$backupCursor'  with "backup cursor".
It is more natural in this context.

2025-07-15 14:42 UTC, igorsol commented on docs/initial-sync.md
> +6. The node internally moves the downloaded files to the local `dbPath`, applies oplog on top, reconstructs timestamps to ensure data consistency.
The __target__ node

2025-07-15 14:42 UTC, igorsol commented on docs/initial-sync.md
> +These configuration parameters can be used to control the file-copy-based initial sync flow. You can set them only at startup.
"file-copy-based" should be "file copy-based"

2025-07-15 14:42 UTC, igorsol commented on docs/initial-sync.md
> +* You cannot use the same sync source for multiple syncing nodes
Single node cannot be used as a sync source for more than one target node simultaneously because only one backup cursor can exist at any moment.

2025-07-15 14:42 UTC, igorsol commented on docs/psmdb-pro.md
> +| [File copy based initial sync](initial-sync.md) | [7.0.21-12](release_notes/7.0.21-12.md) | File copy based initial sync is a new method of syncing data between nodes in a cluster. It is faster tha
Consider replacing "a new method" with "an additional method"

2025-07-15 14:42 UTC, igorsol commented on docs/psmdb-pro.md
> +| [File copy based initial sync](initial-sync.md) | [7.0.21-12](release_notes/7.0.21-12.md) | File copy based initial sync is a new method of syncing data between nodes in a cluster. It is faster tha
"method of syncing data between nodes in a cluster" might be misleading. More technically correct way to say this is:
> method of doing initial sync for the new node in a replica set

2025-07-15 15:46 UTC, nastena1606 commented on docs/initial-sync.md
> +You can only set this configuration at startup.
I'd leave the active voice. Replaced configuration with server parameter.

2025-07-16 11:41 UTC, radoslawszulgo commented on docs/psmdb-pro.md
> +| [File copy-based initial sync](initial-sync.md) | [7.0.21-12](release_notes/7.0.21-12.md) | File copy based initial sync is an additional method of doing an initial sync for a new node in a replica
```suggestion
| [File copy-based initial sync](initial-sync.md) | [7.0.21-12](release_notes/7.0.21-12.md) | File copy-based initial sync is an additional method of doing an initial sync for a new node in a replica set. It is faster for big databases than the logical sync method as it copies physical files rather than cloning data. |
```

2025-07-16 14:27 UTC, igorsol approved these changes

2025-07-24 10:44 UTC, radoslawszulgo commented on docs/initial-sync.md
> +In [Percona Server for MongoDB Pro](psmdb-pro.md), you can choose a file copy-based initial sync for a new node. You must have WiredTiger defined as the storage.
If user build on their own - it's not "Pro" - so we should generally say it's in PSMDB.
```suggestion
In Percona Server for MongoDB, you can choose a file copy-based initial sync for a new node. You must have WiredTiger defined as the storage.
```

2025-07-24 10:46 UTC, radoslawszulgo commented on docs/initial-sync.md
> +File copy-based initial sync method is a physical copying of the data files from the source to the target. It is much faster than the default [logical initial sync :octicons-link-external-16:](https:
```suggestion
The file copy-based initial sync method is a physical copying of the data files from the source to the target. It is much faster than the default [logical initial sync :octicons-link-external-16:](https://www.mongodb.com/docs/manual/core/replica-set-sync/#logical-initial-sync-process) for big datasets (500GB+), which is especially beneficial in heavy write environments. Using this initial sync method speeds up cluster scaling and increases restore performance. 
```

2025-07-24 10:46 UTC, radoslawszulgo commented on docs/initial-sync.md
> +File copy-based initial sync implementation is compatible with that of MongoDB Advanced and has the same [configuration parameters](#configuration-parameters).
```suggestion
File copy-based initial sync implementation is compatible with that of MongoDB Enterprise Advanced and has the same [configuration parameters](#configuration-parameters).
```

2025-07-24 13:30 UTC, radoslawszulgo commented
I'd change the file name to fcbis-initial-sync.md or something. As there's also logical initial sync - the name of the file (and the URL) might be misleading.

2025-07-24 13:31 UTC, radoslawszulgo commented on docs/initial-sync.md
> +* If you're using encrypted storage, Percona Server for MongoDB applies the encryption key from the sync source node to secure the data on the syncing node.
Please add initial sync doesn't work for in-memory storage engine

2025-07-24 13:39 UTC, nastena1606 commented on docs/initial-sync.md
> +* If you're using encrypted storage, Percona Server for MongoDB applies the encryption key from the sync source node to secure the data on the syncing node.
Percona Memory Engine?

2025-07-24 16:35 UTC, radoslawszulgo commented on docs/fcbis.md
> +In Percona Server for MongoDB, you can choose a file copy-based initial sync for a new node. You must have WiredTiger defined as the storage.
```suggestion
In Percona Server for MongoDB, you can choose a file copy-based initial sync for a new node. 
```

2025-07-24 16:36 UTC, radoslawszulgo commented on docs/fcbis.md
> +
I'd appreciate a full configuration example with all the options

2025-07-25 09:37 UTC, nastena1606 commented on docs/fcbis.md
> +
As discussed with @igorsol we don't want users to mess with these params. yes, we list it. And the defaults should be enough. The way how to enable FCBIS is given.
@igorsol please confirm

2025-07-28 10:41 UTC, igorsol commented on docs/fcbis.md
> +
I agree that its is enough to list parameters with descriptions. By default FCBIS should work with default parameters. Only dbadmins with good understanding of the topic should try to alter those parameters. I assume they know how to put parameter into config file.

2025-07-28 13:44 UTC, merged