Psmdb 1518 release notes 7.0.14 9
percona/psmdb-docs pull request #916
Opened 2024-09-03 10:39 UTC by nastena1606

2024-09-04 06:40 UTC, radoslawszulgo approved these changes

2024-09-05 07:19 UTC, radoslawszulgo commented on docs/release_notes/7.0.14-8.md
> +### Enhanced Telemetry for better product usage reporting
it was already last release? No?
https://docs.percona.com/percona-server-for-mongodb/7.0/release_notes/7.0.12-7.html

2024-09-09 11:13 UTC, igorsol approved these changes

2024-09-10 14:46 UTC, sandraromanchenko requested changes

2024-09-10 14:46 UTC, sandraromanchenko commented on docs/release_notes/7.0.14-8.md
> +fully-compatible, drop-in replacement for MongoDB Community Edition 7.0.12.
```suggestion
fully-compatible, drop-in replacement for MongoDB Community Edition 7.0.14.
```

2024-09-10 14:49 UTC, nastena1606 commented on variables.yml
>  mongosh: '2.2.10'
```suggestion
mongosh: '2.3.0'
```

2024-09-23 11:48 UTC, merged