PSMDB-1487 Updated Readme and Contributing guides for 8.0
percona/psmdb-docs pull request #937
Opened 2024-10-09 15:45 UTC by nastena1606

modified:   CONTRIBUTING.md
	modified:   README.md

2024-10-28 08:20 UTC, sandraromanchenko requested changes

2024-10-28 08:20 UTC, sandraromanchenko commented on CONTRIBUTING.md
> +Make sure that your local branch and the branch you merge changes from are the same. So if you are on ``0.0`` branch, merge changes from ``upstream/8.0``.
```suggestion
Make sure that your local branch and the branch you merge changes from are the same. So if you are on ``8.0`` branch, merge changes from ``upstream/8.0``.
```

2024-10-28 12:50 UTC, sandraromanchenko approved these changes

2024-12-10 10:55 UTC, radoslawszulgo commented on CONTRIBUTING.md
>  - 5.0
```suggestion
- 5.0 (EOL)
```

2024-12-10 11:12 UTC, radoslawszulgo approved these changes

2024-12-17 16:07 UTC, merged