PSMDB-1559 Release notes 7.0.15-9
percona/psmdb-docs pull request #945
Opened 2024-11-21 10:48 UTC by nastena1606

new file:   docs/release_notes/7.0.15-9.md
	modified:   docs/release_notes/index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-11-21 12:20 UTC, radoslawszulgo requested changes
Please also add a reference to the "upgrade to minor version" page that mention adjustments in configuration file (fork: true)

2024-11-21 12:20 UTC, radoslawszulgo commented on docs/release_notes/7.0.15-9.md
> +    This release of Percona Server for MongoDB includes a fix for a security vulnerability [CVE-2024-10921](https://nvd.nist.gov/vuln/detail/CVE-2024-10921). This vulnerability allowed an authorized
```suggestion
    This release of Percona Server for MongoDB includes a fix for a security vulnerability [CVE-2024-10921](https://nvd.nist.gov/vuln/detail/CVE-2024-10921). This vulnerability allowed an authorized user to trigger server crashes or receive the contents of the buffer over-reads of the server memory by sending specially crafted requests that constructed malformed BSON in MongoDB. 
```

2024-11-21 12:20 UTC, radoslawszulgo commented on docs/release_notes/7.0.15-9.md
> +    Users running any minor version of Percona Server for MongoDB 6.0.x before 6.0.18 and Percona Server for MongoDB 7.0.x before 7.0.15 should upgrade to Percona Server for MongoDB 6.0.18-16 and 7.0
```suggestion
    Users running any minor version of Percona Server for MongoDB 7.0.x before 7.0.15-9 should upgrade to this version as soon as possible. 
```

2024-11-25 12:19 UTC, igorsol requested changes

2024-11-25 12:19 UTC, igorsol commented on docs/release_notes/7.0.15-9.md
> +* [PSMDB-1539](https://perconadev.atlassian.net/browse/PSMDB-1539) - Removed the fork:true and pidfile management to simplify migration
This fix was reverted by https://github.com/percona/percona-server-mongodb/pull/1346

2024-11-25 16:38 UTC, sandraromanchenko approved these changes

2024-11-25 16:38 UTC, sandraromanchenko commented on variables.yml
> +mongosh: '2.3.2024-09-23'
```suggestion
mongosh: '2.3.2'
```

2024-11-25 16:39 UTC, sandraromanchenko commented on docs/release_notes/7.0.15-9.md
> +    This release of Percona Server for MongoDB includes a fix for a security vulnerability [CVE-2024-10921](https://nvd.nist.gov/vuln/detail/CVE-2024-10921). This vulnerability allowed an authorized
```suggestion
    This release of Percona Server for MongoDB includes a fix for a security vulnerability [CVE-2024-10921](https://nvd.nist.gov/vuln/detail/CVE-2024-10921). This vulnerability allowed an authorized user to trigger server crashes or receive the contents of the buffer over-reads of the server memory by sending specially crafted requests that constructed malformed BSON in MongoDB. The issue is fixed and included in Percona Server for MongoDB 7.0.15-9.    
```

2024-11-26 07:17 UTC, sandraromanchenko approved these changes

2024-11-26 13:43 UTC, radoslawszulgo approved these changes

2024-11-26 17:46 UTC, igorsol approved these changes

2024-11-27 14:36 UTC, merged