PSMDB-1558 Release notes 6.0.19-16
percona/psmdb-docs pull request #947
Opened 2024-11-21 11:59 UTC by nastena1606

new file:   docs/release_notes/6.0.19-16.md
	modified:   docs/release_notes/index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-11-21 12:05 UTC, radoslawszulgo commented on docs/release_notes/6.0.19-16.md
> +    This release of Percona Server for MongoDB includes a fix for a security vulnerability [CVE-2024-10921](https://nvd.nist.gov/vuln/detail/CVE-2024-10921). This vulnerability allowed an authorized
```suggestion
    This release of Percona Server for MongoDB includes a fix for a security vulnerability [CVE-2024-10921](https://nvd.nist.gov/vuln/detail/CVE-2024-10921). This vulnerability allowed an authorized user to trigger server crashes or receive the contents of the buffer over-reads of the server memory by sending specially crafted requests that constructed malformed BSON in MongoDB. In case you want to upgrade to the following major version, the fix is also included in the Percona Server for MongoDB 7.0.15-9.    
```

2024-11-21 12:07 UTC, radoslawszulgo commented on docs/release_notes/6.0.19-16.md
> +    Users running any minor version of Percona Server for MongoDB 6.0.x before 6.0.18 and Percona Server for MongoDB 7.0.x before 7.0.15 should upgrade to Percona Server for MongoDB 6.0.18-16 and 7.0
```suggestion
    Users running any minor version of Percona Server for MongoDB 6.0.x before 6.0.18-16 should upgrade to this version as soon as possible. 
```

2024-11-21 12:09 UTC, radoslawszulgo commented on docs/release_notes/6.0.19-16.md
> +* [PSMDB-1539](https://perconadev.atlassian.net/browse/PSMDB-1539) - Removed the fork:true and pidfile management to simplify migration.
```suggestion
* [PSMDB-1539](https://perconadev.atlassian.net/browse/PSMDB-1539) - Removed the fork:true and pidfile management to simplify migration from the upstream versions.  
```

2024-11-21 12:11 UTC, radoslawszulgo requested changes
Let's keep release notes for 6.x relevant for 6.x situation and not mix with other majors. Also I ask to avoid mentions of the upstream if not relevant.

2024-11-21 15:05 UTC, radoslawszulgo approved these changes

2024-11-25 16:45 UTC, sandraromanchenko requested changes

2024-11-25 16:45 UTC, sandraromanchenko commented on docs/release_notes/6.0.19-16.md
> +* [PSMDB-1539](https://perconadev.atlassian.net/browse/PSMDB-1539) - Removed the fork:true and pidfile management to simplify migration.
```suggestion
```

2024-11-25 16:45 UTC, sandraromanchenko commented on docs/release_notes/6.0.19-16.md
> +    This release of Percona Server for MongoDB includes a fix for a security vulnerability [CVE-2024-10921](https://nvd.nist.gov/vuln/detail/CVE-2024-10921). This vulnerability allowed an authorized
```suggestion
    This release of Percona Server for MongoDB includes a fix for a security vulnerability [CVE-2024-10921](https://nvd.nist.gov/vuln/detail/CVE-2024-10921). This vulnerability allowed an authorized user to trigger server crashes or receive the contents of the buffer over-reads of the server memory by sending specially crafted requests that constructed malformed BSON in MongoDB. The issue is fixed and included in Percona Server for MongoDB 6.0.19-16. If you wish to [upgrade to the following major version](../install/upgrade-from-50.md), the fix is also included in Percona Server for MongoDB 7.0.15-9.    
```

2024-11-25 16:45 UTC, sandraromanchenko commented on docs/release_notes/6.0.19-16.md
> +    Users running any minor version of Percona Server for MongoDB 6.0.x before 6.0.18-16 should upgrade to this version as soon as possible.
```suggestion
    Users running any minor version of Percona Server for MongoDB 6.0.x before 6.0.19-16 should upgrade to this version as soon as possible. 
```

2024-11-25 16:45 UTC, sandraromanchenko commented on variables.yml
> +mongosh: '2.3.3'
```suggestion
mongosh: '2.3.2'
```

2024-11-26 07:19 UTC, sandraromanchenko approved these changes

2024-11-28 15:07 UTC, merged